services:
  e-commerce-service:
    container_name: e_commerce_db
    image: postgres:16-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=e_commerce_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234!
    volumes:
      - ./db_data:/var/lib/postgresql/data
